tasks:
  - before: bash -c "sudo curl https://get.ignite.com/cli! | sudo bash"
    init: sudo bash -c "/usr/local/bin/ignite completion bash > /etc/bash_completion.d/ignite" && /usr/local/bin/ignite scaffold chain chain --path "." --address-prefix ""
    command: clear && echo "CLI Installed, New Project Scaffolded, Ready to go!"
